Name: LDXF
Host: 127.0.0.1
Port: 8800
local: "zh"
mysql:
  DataSource: "root:123456@tcp(127.0.0.1:3306)/sj_cms_new?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  host: "127.0.0.1"
  port: 6379
  pass: ""

jwt:
  secret_key: "gin-randomkey-Xy8!YW&oboSl8a&E+LbiUguRogfO@Hci"
  jwt_header_key: "Authorization"
  jwt_prefix: "Bearer "
  jwt_expire_hour: 24

log:
  level: "debug"
  path: "log" #  日志文件位置
  filename: "sj_cms_log"  # 日志文件名
  max_size: 100 # 进行切割之前,日志文件的最大大小(MB为单位)
  max_age: 100  # 保留旧文件的最大天数
  max_backups: 100 # 保留旧文件的最大个数
  compress: false # 是否压缩
  stacktrace_key: "123213" #
  format: "json"  # 序列化格式

base-data:
  admin-user:
    username: '超级管理员'
    phone: '18888888888'
    password: 'kyk12345678'
  cate-list:
    - '基金类'
    - '保险类'
    - '客户营销类'
    - '其他类'
